<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="ServerDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ae659b64-39d4-4e4c-ab01-a30200dd1f52.sqlserver.sequelizer.com;Persist Security Info=True;User ID=byddnjvjybfymsnq" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AnswerFillBlanks" Member="AnswerFillBlanks">
    <Type Name="AnswerFillBlank">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnswerIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ListAnswers" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CorrectAnswer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Question_AnswerFillBlank" Member="Question" ThisKey="QuestionID" OtherKey="QuestionID" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionType" Member="QuestionTypes">
    <Type Name="QuestionType">
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QuestionType_Question" Member="Questions" ThisKey="TypeID" OtherKey="Type" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.AnswerFindBugs" Member="AnswerFindBugs">
    <Type Name="AnswerFindBug">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WidthPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="HeightPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TopPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="LeftPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Question_AnswerFindBug" Member="Question" ThisKey="QuestionID" OtherKey="QuestionID" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AnswerMultiChoices" Member="AnswerMultiChoices">
    <Type Name="AnswerMultiChoice">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnswerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ListAnswerMC_AnswerMultiChoice" Member="ListAnswerMC" ThisKey="AnswerID" OtherKey="AnswerID" Type="ListAnswerMC" IsForeignKey="true" />
      <Association Name="Question_AnswerMultiChoice" Member="Question" ThisKey="QuestionID" OtherKey="QuestionID" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Games" Member="Games">
    <Type Name="Game">
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WinerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Player_Game" Member="Player" ThisKey="WinerID" OtherKey="PlayerID" Type="Player" IsForeignKey="true" />
      <Association Name="Player_Game1" Member="Player1" ThisKey="LoserID" OtherKey="PlayerID" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Histories" Member="Histories">
    <Type Name="History">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rright" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Wrong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Player_History" Member="Player" ThisKey="PlayerID" OtherKey="PlayerID" Type="Player" IsForeignKey="true" />
      <Association Name="Question_History" Member="Question" ThisKey="QuestionID" OtherKey="QuestionID" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ListAnswerMC" Member="ListAnswerMCs">
    <Type Name="ListAnswerMC">
      <Column Name="AnswerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ListAnswerMC_AnswerMultiChoice" Member="AnswerMultiChoices" ThisKey="AnswerID" OtherKey="AnswerID" Type="AnswerMultiChoice" />
    </Type>
  </Table>
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PlayerLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlayerPoint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Win" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lose" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Player_Game" Member="Games" ThisKey="PlayerID" OtherKey="WinerID" Type="Game" />
      <Association Name="Player_Game1" Member="Games1" ThisKey="PlayerID" OtherKey="LoserID" Type="Game" />
      <Association Name="Player_History" Member="Histories" ThisKey="PlayerID" OtherKey="PlayerID" Type="History" />
    </Type>
  </Table>
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Question">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuestionDif" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SRC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Question_AnswerFillBlank" Member="AnswerFillBlanks" ThisKey="QuestionID" OtherKey="QuestionID" Type="AnswerFillBlank" />
      <Association Name="Question_AnswerFindBug" Member="AnswerFindBugs" ThisKey="QuestionID" OtherKey="QuestionID" Type="AnswerFindBug" />
      <Association Name="Question_AnswerMultiChoice" Member="AnswerMultiChoices" ThisKey="QuestionID" OtherKey="QuestionID" Type="AnswerMultiChoice" />
      <Association Name="Question_History" Member="Histories" ThisKey="QuestionID" OtherKey="QuestionID" Type="History" />
      <Association Name="QuestionType_Question" Member="QuestionType" ThisKey="Type" OtherKey="TypeID" Type="QuestionType" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.correctQuestion" Method="correctQuestion">
    <Parameter Name="Player" Parameter="player" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="QuestionID" Parameter="questionID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.wrongQuestion" Method="wrongQuestion">
    <Parameter Name="Player" Parameter="player" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="QuestionID" Parameter="questionID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.get_all_player" Method="get_all_player">
    <ElementType Name="get_all_playerResult">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PlayerLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlayerPoint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Win" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lose" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_all_questions_history" Method="get_all_questions_history">
    <ElementType Name="get_all_questions_historyResult">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuestionDif" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Correct" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Wrong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_fillBlank_byID" Method="get_fillBlank_byID">
    <Parameter Name="QuestionID" Parameter="questionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="get_fillBlank_byIDResult">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuestionDif" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SRC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AnswerIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ListAnswers" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CorrectAnswer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_findbugs_byID" Method="get_findbugs_byID">
    <Parameter Name="QuestionID" Parameter="questionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="get_findbugs_byIDResult">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuestionDif" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SRC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WidthPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="HeightPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TopPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="LeftPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_mulichoice_byID" Method="get_mulichoice_byID">
    <Parameter Name="QuestionID" Parameter="questionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="get_mulichoice_byIDResult">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuestionDif" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SRC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_player_info" Method="get_player_info">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="get_player_infoResult">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PlayerLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlayerPoint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Win" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lose" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_question_byID" Method="get_question_byID">
    <Parameter Name="QuestionID" Parameter="questionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="get_question_byIDResult">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuestionDif" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SRC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WidthPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="HeightPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TopPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="LeftPoint" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_question_type" Method="get_question_type">
    <Parameter Name="QuestionID" Parameter="questionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="get_question_typeResult">
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.inser_FindBugs" Method="inser_FindBugs">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="qid" Type="System.Int32" DbType="Int" />
    <Parameter Name="width" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="heigh" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="top" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="left" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.inser_MultiChoice" Method="inser_MultiChoice">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="qid" Type="System.Int32" DbType="Int" />
    <Parameter Name="AnsID" Parameter="ansID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_fillBlanks" Method="insert_fillBlanks">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="qID" Type="System.Int32" DbType="Int" />
    <Parameter Name="index" Type="System.Int32" DbType="Int" />
    <Parameter Name="listAns" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="answ" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Insert_Player" Method="Insert_Player">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_question" Method="insert_question">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="type" Type="System.Int32" DbType="Int" />
    <Parameter Name="dif" Type="System.Int32" DbType="Int" />
    <Parameter Name="src" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.question_report_by_name" Method="question_report_by_name">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="question_report_by_nameResult">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Rright" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Wrong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Random_question_by_dif" Method="Random_question_by_dif">
    <Parameter Name="dif" Type="System.Int32" DbType="Int" />
    <ElementType Name="Random_question_by_difResult">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.update_player_info" Method="update_player_info">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Level" Parameter="level" Type="System.Int32" DbType="Int" />
    <Parameter Name="Point" Parameter="point" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.update_point" Method="update_point">
    <Parameter Name="Win" Parameter="win" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="WinPoint" Parameter="winPoint" Type="System.Int32" DbType="Int" />
    <Parameter Name="Loser" Parameter="loser" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LosePoint" Parameter="losePoint" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.get_games_by_Name" Method="get_games_by_Name">
    <Parameter Name="player_name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="get_games_by_NameResult">
      <Column Name="GameID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WinerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_player_name" Method="get_player_name">
    <Parameter Name="playerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="get_player_nameResult">
      <Column Name="PlayerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>