//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRSever
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerMultiChoices
    {
        public int ID { get; set; }
    
        public virtual ListAnswerMC ListAnswerMC { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
