<?xml version="1.0" encoding="utf-8"?><Database Name="db7a44969a30f24bdd9762a2fa008c96a5" Class="dataAppHabourDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=7a44969a-30f2-4bdd-9762-a2fa008c96a5.sqlserver.sequelizer.com;Initial Catalog=db7a44969a30f24bdd9762a2fa008c96a5;Persist Security Info=True;User ID=hecnpillwnfocgbc" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db7a44969a30f24bdd9762a2fa008c96a5ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblPlayer" Member="tblPlayers">
    <Type Name="tblPlayer">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PlayerLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlayerPoint" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>