//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRSever
{
    using System;
    using System.Collections.Generic;
    
    public partial class Histories
    {
        public int PlayerID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> Rright { get; set; }
        public Nullable<int> Wrong { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Players Players { get; set; }
    }
}
