//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRSever
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListAnswerMC
    {
        public ListAnswerMC()
        {
            this.AnswerMultiChoices = new HashSet<AnswerMultiChoices>();
        }
    
        public int AnswerID { get; set; }
        public string Answer { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AnswerMultiChoices> AnswerMultiChoices { get; set; }
    }
}
