//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRSever
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapstoneEntities4 : DbContext
    {
        public CapstoneEntities4()
            : base("name=CapstoneEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnswerFillBlanks> AnswerFillBlanks { get; set; }
        public DbSet<AnswerFindBugs> AnswerFindBugs { get; set; }
        public DbSet<AnswerMultiChoices> AnswerMultiChoices { get; set; }
        public DbSet<listMatches> listMatches { get; set; }
        public DbSet<Histories> Histories { get; set; }
        public DbSet<ListAnswerMC> ListAnswerMC { get; set; }
        public DbSet<Players> Players { get; set; }
        public DbSet<Questions> Questions { get; set; }
        public DbSet<QuestionType> QuestionType { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
